### ISSUE TITLE
Incoherent pubkey type

### ISSUE THREAD

**Issue by diasdavid** [diasdavid/js-peer-id#9]
I've found this while debugging swarm identify protocol. It seems that the pubkey is stored as a _string_ if derived from priv key and it is a _buffer_ if the pubkey is passed directly.

buffer -> https://github.com/diasdavid/js-peer-id/blob/master/src/index.js#L133-L135
string -> https://github.com/diasdavid/js-peer-id/blob/master/src/index.js#L163

I'm ok both, although I expected it to be a buffer (like it was before). @nginnever what is your input on this.

**Comment by nginnever** [comment]
Aha so when we derive the ID from passing in a public key, I wasn't actually sure what the source of that public key was or how it would be formatted. In our tests we supply it with a string formatted public key (I might have changed this from a buffer?). So when creating an ID from a public key it will simply store the public key in whatever format you supply it. 

So if our system will always supply deriving an ID from a public key as a buffer, then I should add a line to creating from a private key that will transform the string to a base64 buffer as well for consistency I suppose. 

Keep in mind that if we do supply deriving an ID from a public with a buffer then we technically buffer a buffer <a href ="https://github.com/diasdavid/js-peer-id/blob/master/src/index.js#L133">on this line</a>. It does come out with the same result but this line would probably not be needed. 

Let me know what you think about the consistency and double buffering and if you want I will add a line to the private key function to make sure it stores a buffer of the public key for consistency.

**Comment by diasdavid** [comment]
> Aha so when we derive the ID from passing in a public key, I wasn't actually sure what the source of that public key was or how it would be formatted. In our tests we supply it with a string formatted public key (I might have changed this from a buffer?). So when creating an ID from a public key it will simply store the public key in whatever format you supply it.

> So if our system will always supply deriving an ID from a public key as a buffer, then I should add a line to creating from

Let's make it always a buffer by default then :)

> Keep in mind that if we do supply deriving an ID from a public with a buffer then we technically buffer a buffer on this line. It does come out with the same result but this line would probably not be needed.

Same applies for the privateKey. It should be specified what is the input encoding format and what is the format that both keys are available. Also, to make this more obvious since it might lead to errors, let's get commented on top of the function signatures which types are they expecting in their args.

**Comment by diasdavid** [comment]
thank you for fixing this :)
